apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configmapref
  name: configmapref
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmapref
  template:
    metadata:
      labels:
        app: configmapref
    spec:
      containers:
      - image: sysnet4admin/sleepy 
        name: sleepy 
        envFrom:
        - configMapRef:
            name: nginx-config
        command: ["/bin/sh","-c"]
        args:
        - |
          echo "sleepy is $STATUS"
          echo "NOTE: $NOTE"
          sleep 3600
        envFrom:
        - configMapRef:
            name: sleepy-config
