apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  name: default
  namespace: kube-public
spec:
  authentication:
  - name: oidc
    oidc:
      # should change clientSecret after applying keycloak
      clientSecret: 118K6KJTJxMeDwyMjT8HkqEPC3qW5vc5
      clientID: k8s-auth 
      cloudConsoleRedirectURI: https://console.cloud.google.com/kubernetes/oidc
      extraParams: resource=token-groups-claim
      groupPrefix: '-'
      groupsClaim: groups
      issuerURI: https://oncloud-1.site/realms/kubernetes
      kubectlRedirectURI: http://localhost:8000
      scopes: openid
      userClaim: preferred_username
      userPrefix: '-'
  internalServer: ""
  name: hj-keycloak-oncloud-1-gke
  # server: manually input after applying clientconfig or searching and add 
status: {}
